### ISSUE TITLE
multiple stripe account

### ISSUE THREAD

**Issue by seb-sykio** [isaacsanders/omniauth-stripe-connect#50]
hi,

on our plateform, we deal with multiple stripe account. we also use devise. 

I saw :
config.omniauth :stripe_connect, "STRIPE_CONNECT_CLIENT_ID", "STRIPE_SECRET"

Is it possible to set the "STRIPE_CONNECT_CLIENT_ID" and "STRIPE_SECRET" dynamically for each request ?

thanks

**Comment by isaacsanders** [comment]
This seems like the wrong way to use this feature. I might be wrong.

**Comment by phstc** [comment]
@isaacsanders I have a similar need. For my test users `User#mode=test`, I would like to connect them to my Stripe test account, which has a different set of keys. 

![image](https://user-images.githubusercontent.com/105652/42738904-25529ddc-885a-11e8-998b-c36bbcd83fc4.png)

These "test users" are just for testing purposes, and using a test account allows me to place orders with fake credit cards `4111 1111 1111 1111`.

**Comment by isaacsanders** [comment]
@seb-sykio @phstc 

I will consider this feature if:

- Someone else makes a Pull Request.
- The approach used in the Pull Request is used by another popular omniauth strategy library.

I am not going to work on this feature, because I think it is a code smell, and I have other things I would rather do. But if this is important enough to either of you two, then I will consider the pull request.

**Comment by phstc** [comment]
Hi @isaacsanders

I wouldn't call it a code smell, since it is a valid business need.

Anyway, I don't really think this is a responsibility of `omniauth-stripe-connect`, this should be something in `omniauth` directly. Which is supposed to be supported already:

- https://github.com/omniauth/omniauth/wiki/Managing-Multiple-Providers
- https://github.com/omniauth/omniauth/wiki/Dynamic-Providers
- https://www.createdbypete.com/articles/dynamic-omniauth-provider-setup/
- http://www.ur-ban.com/2011/04/30/devise-omniauth-dynamic-providers/

I tried a few options, but I couldn't make them work with `omniauth-stripe-connect` yet, maybe there's something that needs to be updated on this strategy, I will play more with it, and create a pull request in case it makes sense.

Thanks checking back this issue and of course for `omniauth-stripe-connect` 👏

**Comment by isaacsanders** [comment]
@phstc I look forward to your pull request.

Just to clarify, are you interested in a different configuration on each request, or a different configuration as per the deploy environment? The original issue was for something different than the examples you provided, if I'm reading it right.
